---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_zero
  data_bags_path: 'chef/data_bags'

platforms:
  - name: ubuntu-14.04

suites:
  - name: demoapp
    run_list: recipe[demoapp]
    attributes:
